server:
  port: 8010
spring:
  application:
    name: pavis-upms-service
  rabbitmq:
    host: 188.131.193.107
    port: 5672
    username: guest
    password: guest
  redis:
    host: 188.131.193.107
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://188.131.193.107:3306/upms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Semi.1001
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.pavis.upmsservice.model
  global-config:
    db-config:
      id-type: auto