server:
  port: 8010
spring:
  application:
    name: pavis-upms-service
  rabbitmq:
    host: 188.131.193.107
    port: 5672
    username: guest
    password: guest
  redis:
    host: 188.131.193.107
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://188.131.193.107:3306/upms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Semi.1001
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.pavis.upmsservice.model
  global-config:
    db-config:
      id-type: auto
security:
  oauth2:
    client:
      client-id: pavis-web-service
      client-secret: 123456
      access-token-uri: http://188.131.193.107:8090/oauth/token
      user-authorization-uri: http://188.131.193.107:8090/oauth/authorize
    resource:
      # 很重要
      token-info-uri: http://188.131.193.107:8090/oauth/check_token
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug